"""Add chat

Revision ID: 2b37eaf280e9
Revises: 20495e7dda92
Create Date: 2025-10-14 17:31:21.221258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b37eaf280e9'
down_revision: Union[str, Sequence[str], None] = '20495e7dda92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_pass_check', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pass_check')
    # ### end Alembic commands ###
