"""Re

Revision ID: bcf7d3c4e63a
Revises: c3b7c41d15c4
Create Date: 2025-10-06 17:06:55.558218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf7d3c4e63a'
down_revision: Union[str, Sequence[str], None] = 'c3b7c41d15c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'two_fa_auth',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'two_fa_auth',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
