"""Re1

Revision ID: e07b0d983905
Revises: bcf7d3c4e63a
Create Date: 2025-10-06 17:12:49.343894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07b0d983905'
down_revision: Union[str, Sequence[str], None] = 'bcf7d3c4e63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'phone_verified',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_verified',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
