"""Add users role_id

Revision ID: f334ebe5c9b8
Revises: eecc6bfd5ba2
Create Date: 2025-10-08 01:44:43.854098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f334ebe5c9b8'
down_revision: Union[str, Sequence[str], None] = 'eecc6bfd5ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_nick',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.drop_constraint(op.f('users_user_nick_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_user_nick'), 'users', ['user_nick'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_nick'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_unique_constraint(op.f('users_user_nick_key'), 'users', ['user_nick'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('users', 'user_nick',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
